### ISSUE TITLE
 Fitlog－项目提议

### ISSUE THREAD

**Issue by guoyuming** [guoyuming/Fitlog#3]
# Fitlog－项目提议
## 目标用户
一直在健身训练的人，他们有如下特点：
1. 每周至少三次运动
2. 自己，或教练帮忙，定制健身计划
3. 训练前出计划，训练之后记录备案，可能写在小本本、备忘app、健身房小黑板上
4. 希望做得更好，跑更快、举更重、跳更久，训练计划会迭代进步；迭代的基础是之前的计划

## 内容构建
1. 从运动、训练教材中选取训练动作，构建动作库：身体部位－动作名称的二级列表
2. 建立训练模版，
	- 负重动作：动作名称－负重－组数－次数的单项列表，比如哑铃卧推－10kg－五组－每组10次
	- 有氧运动：动作名称－时间，比如健身操－20分钟
	- 跑步：跑步－公里数
		
3. 训练动作自动进阶：
	- 负重动作：下次训练负重＝某次训练负重＊110%；比如，某次最小训练动作：哑铃卧推－10kg－五组－每组10次，下次最小训练动作：哑铃卧推－11kg－五组－每组10次
	- 有氧运动：不变
	－ 跑步：不变

## 用户操作
1. 新建训练计划
	- 择身体部位－动作名称
	- 选择组数、每组次数
	- 添加动作
	- 重复以上步骤，添加若干动作，
	- 选择完成日期，提交训练计划
	
2. 修改训练计划：选择训练计划，可修改所有字段

3. 当天完成某训练计划，点击完成，并添加花费时间，记录到timelog

4. 计划进阶：重复使用某套训练计划，改计划内动作自动在重量上进阶

## 进阶功能：
1. 按负重统计公斤数、按跑步统计公里数、统计计划花费时间，数据切片图形化展示
2. 根据不同训练需求，写出不同算法，形成不同计划模版和进阶公式

## 难点&工作量
1. 完成基础功能无难点，工作量在内容上构建动作库，大量的数据录入工作
2. 进阶功能1需要研究新的库，比如pandas，有待研究；功能2需要引入更多专业知识，和更复杂的架构。

## 技术&团队
项目提出者掌握编程新手，轻压力下完成各章基础任务，上手flask、html＋css、sqlite、heroku部署；他也是新手产品经理，Axure原型图画得快，熟练梳理app流程和架构。
### 载体
网页或公众号，有待讨论。网页利用bootstrap，展现形式更丰富，公众号更普及并天然离用户更近，如果可以实现网页的导航、列表、输入框等交互，公众号更好。
### 技术配置
完成之前任务所用到的技术是基础，更强大高效的框架、库有待继续折腾。
### 团队期望
小项目，充分沟通，快速行动优先。希望四人以内，无职位／角色一说。有兴趣可以先和我联系，更充分了解相互想法和需求后，再立项分工。

**Comment by guoyuming** [comment]
1011与广鹤讨论纪要：
### 建议：
1. 查看动作库有无API调用
2. 项目还是大了，一起找个mvp，比如，就是统计运动频率和时间

提议参与的部分：做pandas 和数据分析这部分，统计次数和公斤数跟统计时间是一样的。雨明完成其他模块，比如调用api，架构网页和微信等等。

### 后续行动
写出MVP构架，细化功能点，在此异步沟通。

**Comment by liguanghe** [comment]
理想:像支付宝多一个记账本，把额外非支付宝花销记进去，如果我们的记账本可以开通给keep或者其他健身软件的接口，统一统计时间和次数，就会有意思很多。联通记录。
我倾向于客观记录次数和时间，事后统计，原理就是面对真实的自己，逐渐加任务。不过如果添加计划功能，也还是可以的，keep已经有这个功能了，可以看一下。

**Comment by guoyuming** [comment]
立马跑去围观了一下，keep是做了添加计划功能；每个计划里面的动作是规定好的，我们想做你可以自己组合计划中的动作。

**Comment by liguanghe** [comment]
计划一周三十分钟，每周三次，这是最小计划，没有动作的~

NeoClassic <notifications@github.com>于2017年10月12日 周四18:15写道：

**Comment by littlexiaocai** [comment]
从功能角度去梳理了下，有三个功能模块，编写健身计划模块，记录健身数据模块，回顾健身数据模块，@guoyuming ，@liguanghe 不同的功能模块都可以有自己的mvp，我们是否可以基于不同的功能进行mvp细分。

## 写健身计划
### 写什么时候的健身计划
1. 只写当天的健身计划
2. 可以写指定时间的计划
### 如何写健身计划
1. 基于健身部位新建健身计划，并可以变成模板
2. 调用模板写计划，修改对应项目的负重，次数和运动时间

## 记录健身数据
### 什么时候记录健身数据
1. 健身过程中记录
2. 健身完记录
### 如何记录健身数据
1.  不基于模板，随意记录
2.  基于不同的健身计划模板记录
### 记录什么健身数据
1. 对应项目的负重
2. 对应项目的次数
3. 对应项目的运动时间
## 回顾历史数据
### 如何呈现历史数据
1. 按照日期，直接显示所有记录的数据
2. 如果根据健身计划模板记录数据，可以显示完成度

**Comment by liguanghe** [comment]
专攻一个容易做，我们的人员和时间还不适合分散精力，抽一个最小的出来吧。

littlexiaocai <notifications@github.com>于2017年10月13日 周五05:59写道：
