### ISSUE TITLE
Fitly项目MVP&分工计划讨论

### ISSUE THREAD

**Issue by guoyuming** [guoyuming/Fitlog#4]
## 产品架构
在综合伙伴们建议之后，确定MVP架构如下：
![untitled diagram-2](https://user-images.githubusercontent.com/17700597/31549559-266c1bf2-b061-11e7-9253-3ce5a92febba.png)

## 功能说明
三个功能模块：
1. 全局动作库
2. 当日训练MVP
3. 记录分析／图形展示

### 1. 全局动作库
- 所有动作放入一张数据表内，不同动作取不同colunm的值；动作属性不同，没有的值留空；比如跑步动作在重量、组数上取值为空。
- 动作库数据表，colunm值为动作属性集合，字段有：时间、次数、组数、重量、距离……（待补充更多）；index为动作名称。

待讨论问题：为了操作方便，这里是否需要在总表给动作分类，比如按某教材分上肢（卧推、哑铃卧推、哑铃飞鸟、弯举）；下肢（硬拉、深蹲、罗马尼亚硬拉）；全身；核心……等等？

### 2. 当日训练MVP
- 表单操作前端展现形式，参考微博网页版－个人设置模块。
- 符合数据库操作规范应该是，当用户定制好计划之后，个人计划数据表已经生成，这时候就可以提交保存。当用户修改记录时，重新连接数据库，修改个人计划数据表在提交保存。

待讨论问题：因为后面要按日期提取训练记录，所以在设计个人训练数据表时，要加入日期字段，一张表如何实现？

### 3. 记录分析／图形展示
- 这部分可以聚合的维度很多，脑图中只是列出一些可能的维度；我会再从用户场景来调查下，哪几类聚合是对用户最有用。蔡俊提议可以做成api，我们需要哪种维度聚合，自己来选择调用。

## 计划分工
- 如果走通数据，以上三个模块应该是按1、2、3顺序，即先有动作库，再当日训练MVP，再统计分析。我在10月16日之前完成第一个模块，做完动作库。
- 2、3模块可以先写接口，其中的功能点还可以继续分工。我们可以都找找技术方案，有价值的内容可issue留言放出，然后在确定分工。

**Comment by littlexiaocai** [comment]
1. 对于2里的讨论问题，动作模板有一个数据表单，训练数据要有另外一个数据表单，分开存储，训练数据的表单的index用日期字段表示。
2. 细想了下动作模板的表单，这和我们作业时的不同，我们作业时一直用的是一维表单，现在是二维表单。

这就有一个问题，比如有的模板有跑步这个动作如下
<img width="413" alt="screenshot" src="https://user-images.githubusercontent.com/30562762/31558211-932b74dc-b07e-11e7-8d4e-3bd4b9715a19.png">

而有的模板没有跑步这个动作，如下：
<img width="411" alt="screenshot" src="https://user-images.githubusercontent.com/30562762/31558240-ae1d89ce-b07e-11e7-9c8c-0cb68655f440.png">

这就是两个完全不同的表单了。

为了简化，只使用一张表单来表示所有模板，我建议index将所有的动作分类都列出来，然后column增加一个使能栏，用到的动作就enable，没有用到的动作就disable，如下。
<img width="482" alt="screenshot" src="https://user-images.githubusercontent.com/30562762/31558341-0c41bcaa-b07f-11e7-96a7-7113a12032f3.png">

**Comment by littlexiaocai** [comment]
看了会数据库的知识，发现数据库的结构很重要，14号要恶补下数据库设计的知识。

**Comment by littlexiaocai** [comment]
### 动作模板数据库存储形式疑惑
昨晚在看数据库结构时一个疑问：
以前我们建立的数据表，都是基于行来存储检索的，比如
<img width="225" alt="screenshot" src="https://user-images.githubusercontent.com/30562762/31571741-146f1214-b0cb-11e7-9094-01df63b35cea.png">

一条记录对应的就是一行，查询第一条记录就是查一行，查询第二条记录就是查询第二行

但是我们现在建动作模板时，一个模板对应一条记录，但是这条记录可不止一行了，而是整个表。
比如存储一个跑步的动作模板
<img width="477" alt="screenshot" src="https://user-images.githubusercontent.com/30562762/31571778-ab2d93d8-b0cb-11e7-90eb-2b53d6bc9da6.png">

再存储一个硬拉的动作模板

<img width="480" alt="screenshot" src="https://user-images.githubusercontent.com/30562762/31571798-f007b7ae-b0cb-11e7-95cc-3e169ef7ab96.png">

这两个模板 就是两条数据库记录，以什么样的形式存储在数据里？ 这两个模板相当于两个表，模板一多，就会产生更多的表，就要对表进行检索，不过感觉这样不太合理，应该有更优雅的解决方式。

###  健身记录数据库存储疑惑
健身记录数据库一样存在上面的问题，基于日期存储记录，但是这个记录不只是一行数据了，而是一个表的数据，如何存储。

**Comment by littlexiaocai** [comment]
## 数据库结构讨论
今天学习sqlite，解锁了两个新知识点，数据库对应关系和外键。
### 数据库对应关系
首先要了解了数据库的对应关系，一对一，一对多，多对多，可以参考下面这个链接。

[数据对应关系](http://www.cnblogs.com/shuming/archive/2011/01/16/1936957.html)

文中以学生选课为例，学生单独是一个表，课程单独是一个表，但是一个学生可以选择很多门课程，所以学生和课程之间的关系就是一对多的关系。进行类比，我们的动作模版是一个表，动作是一个表，一个模版可以选择不同的动作，模版和动作之间也是一对多的关系。

### 外键

既然确定是一对多的关系，模版的表如何调用动作的表呢？这里引入了一个外键，具体可以参考下面这个链接。

[如何在一个表里引用其他表的数据](http://www.cnblogs.com/myqiao/archive/2011/07/13/2105550.html)

### 动作模版数据结构

比如将动作简化到只有3个动作，跑步，硬拉，飞鸟。需要建立四个表。动作模版表，跑步表，硬拉表，飞鸟表。动作模版表调用其他三个表的数据，如下所示。


其中跑步列下的数字2，表示引用跑步表里的第2个记录。

跑步表如下


硬拉表如下


飞鸟表如下

**Comment by liguanghe** [comment]
项目大小与 MVP 与 组员人数/投入时间/能力 直接相关 -> [24h[ANN] 组员自我介绍 · Issue #5 · guoyuming/Fitlog](https://github.com/guoyuming/Fitlog/issues/5)

**Comment by guoyuming** [comment]
@littlexiaocai 哇～很缜密的想法，关系型数据库和外表引用的新知识点也让我对数据库了解更多。我们之前讨论，对动作模版也许有不同的理解。我想的是，动作模版是否可以不需要建数据表，如果每个动作的有效字段都要有值的话，比如：硬拉－时间10分钟－次数10个－组数六组－重量60kg，那么理论上各种字段不同值组合无限，就会造成你说的需要好多张表。动作模版不需要数据表，是因为用户不需要从表中调取有数值的动作模版，比如他不需要：硬拉－时间10分钟－次数10个－组数六组－重量60kg这样一个动作模版；只需要：硬拉－时间（可填）－次数（可填）－组数（可填）－重量（可填）－距离（不可填）这样的输入交互。所以动作模版的另外一个解决方案可以是前端写死，不需要从数据库取值。

每次用户做计划时候就相当于在新建数据表；只是每天建一张表、训练多少次就建多少张表，是否优雅简洁？如何把日期变量加入表中？不同日期的数据表是否可以整合在一起？

**Comment by littlexiaocai** [comment]
@guoyuming 还好你提醒了，说的对，动作模板可以不用填具体数据，这样可以简化很多。

对于健身数据的存储，为了避免每次健身都重新建一张表，我今天想了想，可以只是用两张表来实现这个健身数据的存储。

首先建立一个**动作库表**，用户每次通过模板新建计划点击提交时，都会将当天需要完成的动作填入这个表，以ID序号自增。

然后建立一个**健身数据表**，以时间为主键，当前限制每次健身最多只有10个动作，动作列里引用的是动作库表里的数据。

比如2017.10.10号的健身记录是做了3个动作，分别是id 为1，2和3的动作，到动作库里查询分别是跑步 10km，硬拉10kg 5次和硬拉5kg 10次。

2017.10.12号做了1，4，5，6共4个动作，到动作库查询分别是跑步10km，飞鸟5kg 5次，跑步 5km和飞鸟 8kg 10次。

这样就可以只通过两张表来记录每天的健身记录了，你看下有没有什么问题，如果可以，我在周二前准备实现一个 健身数据记录的MVP。

**Comment by guoyuming** [comment]
@littlexiaocai  嗯啊，很科学的设计啊，果然数据库设计地好，可以解决好多问题～

确认一下我的理解：动作库（微信中发我的第一张表）是所有用户共用的，这个表的数据来源是用户自己每天写的计划。写入计划时，不同两天写计划，可能会出现以下两种情况（但我后来写回复时候，发现这种情况在你设计的数据库中可以容纳）

1. 用户输入两个以上同样名称动作，但其他字段，比如时间、重量不同。解决：记为两条不同的记录，用ID区分。
2. 用户输入两条完全一样的记录。解决：不新建记录，判断为相同记录之后，在健身数据表直接引用已有的ID值。

健身数据表是每个用户一张，动作模版在健身数据中封装成了一个ID。这个设计神来之笔啊！

**Comment by liguanghe** [comment]
可否将现在思路梳理并输出一个数据形式，以便统计和处理。时间在这张表里是否用到，精度是到天，时，分，还是秒？
最终输出是什么样的？

**Comment by guoyuming** [comment]
@liguanghe 数据形式具体指哪些呢？时间变量MVP中已讨论的字段有两个：1. 制定当日训练计划时的变量，取值是年月日格式的日期；2. 单个训练动作所花费时间，精确到分。

**Comment by liguanghe** [comment]
@guoyuming 
输入的数据是一张表格么, 什么样的表格?
希望看到怎样的输出? 是什么样的表格? 
以上两点可否出一个 demo, 一目了然~

**Comment by guoyuming** [comment]
@liguanghe 单一用户输入的表格数据如下：
![31591137-e877d148-b24e-11e7-809f-e2343316972f](https://user-images.githubusercontent.com/17700597/31641979-e81030de-b31a-11e7-9567-7309aa2a7b31.png)
输出数据最简单demo预计是这样，横轴时间（日为单位），纵轴是总体运动时间（分为单位）
<img width="255" alt="screen shot 2017-10-17 at 9 12 59 am" src="https://user-images.githubusercontent.com/17700597/31642073-8737b844-b31b-11e7-8a93-c132fc8c539a.png">

**Comment by liguanghe** [comment]
@guoyuming 
可以的, 这个简单, 做起来吧. 
要不要三人快速 zoom 一下?

**Comment by guoyuming** [comment]
@liguanghe @littlexiaocai  嗯，你那时差比国内快两小时？ 明天晚上如何？具体时间你建议几点？用微信多人语音也可以。

**Comment by liguanghe** [comment]
zoom 可以录音和共享屏幕，可能比较合适。
我这里比国内快5个小时，你们白天都上班是吧？有没可能你们的中午？或者你们的下午六点？

NeoClassic <notifications@github.com>于2017年10月17日 周二18:54写道：

**Comment by littlexiaocai** [comment]
##  健身数据存储显示MVP

[代码地址](https://github.com/littlexiaocai/Py101-004/tree/master/Chap7/project)
### 实现功能

#### 健身数据存储
在本地运行fit_record_test.py，在网页端输入地址，可以看到下面的界面
![screenshot](https://user-images.githubusercontent.com/30562762/31661260-a57f2ab6-b36c-11e7-99b2-978dbc83b7a8.png)

此界面模拟已经添加了一个模板，此模板最多只能添加10个动作，每个动作的属性都是一样的包含：运动类型，时间，次数，组数，重量，距离，所以在输入参数时，做了省略，想输入跑步10km，直接输入输入“跑步 0 0 0 0 10”，参数之间以空格空开。

操作步骤如下：
1. 输入健身日期，如2017-10-19
2. 输入动作，为了简化，都已空格隔开，注意不要多输空格，会报错
3. 点击提交健身数据

#### 查看健身数据
操作步骤：
1. 点击查看健身数据
2. 在**命令窗口**可以看到历史健身数据如下


#### 清空健身数据
为了避免数据过多，方便调试，设置了一个清空健身数据按钮，直接点击即可。

### 数据库存储接口
数据库接口存储在 database.py。
#### record_movement(movementdata)_
存储动作库数据库，操作的数据库是FITMOVEMENT，里面存储的是运动完后的所有动作数据，数据库内容如下所示。

由于限制了最多10个的动作，参数movementdata 传递是本次运动提交的所有动作，此函数会自增ID将所有动作记录依次存入FITMOVEMENT，并返回本次运动的ID列表，比如本次运动只做了跑步和飞鸟，就会返回序号5和6。供后面的健身数据库使用。

#### record_fitdata(date,fitdata)_

存储健身数据库，如下所示，用于保存每天的健身数据。


此函数的参数date为健身日期，fitdata来自于record_movement的返回值，里面存储的动作库的ID，健身数据库不直接存储动作，存储的是动作库的ID。

#### history_fitdata_
显示所有的健身数据。

#### 存储实例
参考fit_record_test.py的16到22行代码。

**Comment by ZoomQuiet** [comment]
是也乎,(￣▽￣)

- `ODBP`? 面向数据库的开发?
- 不是应该面向目标/问题解决的嗯哼?
    + 动作对健身重要嘛?
    + 健身追踪是什么?
    + 有什么核心指标能最正确的代表健身效果?
- 进行的, 真的是要统计数据:
    + 一定要 RMDB?
    + NoSQL ?
    + 一定要数据库?
    + ...

所以, 第一准则永远是:

- 什么真空问题?
- 如何解决?
- 如何用软件解决?
- ...
