### ISSUE TITLE
24h[ANN] 组员自我介绍

### ISSUE THREAD

**Issue by liguanghe** [guoyuming/Fitlog#5]
- 名号
- 技能
- 投入时间
- ...

**Comment by liguanghe** [comment]
- 李广鹤
- liguanghe.github.io
- 技能: pandas/ numpy/bokeh/ 基本使用及可视化
- 与本项目相关项目及代码: 稍后迁移至本项目分支
- 投入时间: 每周3-5 小时
    - 其他项目: 深度学习 投入20+
    - alt4dama: 10+
    - 新西兰转行程序员: 10+ 

- 请组长考虑全部组员投入时间等设定:
    - 合理的项目目标
    - MVP
    - 时间规划 与 milestone 结合
        - 总共多少周,多少天
        - 一周或三天完成怎样的任务
    - 协同规约
        - issue -> (自动) gmail 查收 issue 更新
        - slack?

**Comment by guoyuming** [comment]
- 郭雨明
- guoyuming.github.io
- 技能: html/css/sqlite/flask/heroku
- 与本项目相关项目及代码: 编写中
- 本项目投入时间: 每周5-8 h
    - 其他项目: 暂无

- 请组长考虑全部组员投入时间等设定:
    - 合理的项目目标：10月30日路演前完成之前确定的MVP
    - MVP：见issue4
    - 时间规划 与 milestone 结合
        - 两周14天
        - milestone待定
    - 协同规约
        - issue -> (自动) gmail 查收 issue 更新
        - zoom 预约会议，或在线语音预约一对一沟通
