### ISSUE TITLE
10月18日第一次zoom线上会议提议

### ISSUE THREAD

**Issue by guoyuming** [guoyuming/Fitlog#6]
- 时间：10月18日 中午12:30
- 背景：项目MVP确定，在课程项目答疑Meetup上初步展示
- 开发进度：完成数据库demo、确定前端展现框架
- 讨论议题：
  1. 大妈在答疑上提示我们，什么数据对健身来说是关键的，也就是记录什么数据，看到它变化，说明健身效果变好了。这个数据，也就是我们在第3个功能模块，统计分析的操作对象。
  2. 各自分工进度、以及遇到的难点
  3. 开发日程计划
- 录音: 链接: https://pan.baidu.com/s/1i53nSrz 密码: 6yjr

**Comment by liguanghe** [comment]
收到 
- 方式： Zoom 线上会议
- 会议 ID： 9039343080
- 密码： debuguself

**Comment by liguanghe** [comment]
录音已上传, 链接见 issue 主文

**Comment by guoyuming** [comment]
## 会议备忘
时间：2017年10月18日 12:30－13:12
### 讨论问题
1. 目标用户：非运动小白，长期做运动训练，每周至少三次，安排进阶训练计划的人

2. 数据分析展示模块，取哪些字段？三个长期运动的阐述自己的见解
- 蔡俊：身体素质变化过程，比如跑更远、举更重，统计运动－属性维度。
- 广鹤：所有运动加总，不记录单独事件或动作，现在在做的时间记录就是所有运动的加总。统计项目－时间维度。
- 雨明：过程管理，今天定训练计划之前，要看之前做过的计划，好进阶。比如上次卧推50kg，这次55kg，统计运动－属性维度。

3. 运动－属性维度统计的颗粒度精确到身体部位，还是训练动作？
如果精确到身体部位，会有一些动作，比如练习腰腹的动作，难以分类到上肢或下肢。不同的训练教科书对不同动作分类不一样；如果要让操作定义科学，需要折腾更多论文或教材。所以从最小行动出发，运动－属性颗粒度精确到训练动作－属性维度。

4. 是时时记录、修改健身数据表，还是有开放和结束时间。
理想情况是时时修改，但考虑到浏览器进程、手机电池状况、缓存等问题，还需讨论解决方案。

### 细节提示
- 广鹤：
	1. 日期输入时候要定义好格式，可以用python内置datetime；、
	2. 给用户开放选择，不用选动作，选了身体部位就可以开始记录；
	
### 达成一致
1. 成员各自的输入和输出
- 广鹤：拿到用户健身数据记录表，输出选定的字段，图形化展示。
- 雨明：输出前端交互，输出路演demo
- 蔡俊：搭建数据库、发开相关接口

2. 开发进度：本周完成mvp

### 下一步行动
#### 待优化的点
1. 用户在网页上操作，如果想时时修改，如何设计交互和数据传输

#### 待讨论问题
1. 选取哪些动作来做统计
2. 统计的时间范围，和时间颗粒度；也就是用户可以查询多久以前的数据，可否按天、周、月、年查询；考虑到如果某天数据为空，图形化展示效果不好

**Comment by liguanghe** [comment]
@guoyuming 待讨论问题建议另开 issue, 把链接放到这个 issue 里. 一事一议~~

**Comment by guoyuming** [comment]
@liguanghe 嗯啊～

**Comment by guoyuming** [comment]
## 会议备忘
时间：2017年10月18日 12:30－13:12
### 讨论问题
1. 目标用户：非运动小白，长期做运动训练，每周至少三次，安排进阶训练计划的人

2. 数据分析展示模块，取哪些字段？三个长期运动的阐述自己的见解
- 蔡俊：身体素质变化过程，比如跑更远、举更重，统计运动－属性维度。
- 广鹤：所有运动加总，不记录单独事件或动作，现在在做的时间记录就是所有运动的加总。统计项目－时间维度。
- 雨明：过程管理，今天定训练计划之前，要看之前做过的计划，好进阶。比如上次卧推50kg，这次55kg，统计运动－属性维度。

3. 运动－属性维度统计的颗粒度精确到身体部位，还是训练动作？
如果精确到身体部位，会有一些动作，比如练习腰腹的动作，难以分类到上肢或下肢。不同的训练教科书对不同动作分类不一样；如果要让操作定义科学，需要折腾更多论文或教材。所以从最小行动出发，运动－属性颗粒度精确到训练动作－属性维度。

4. 是时时记录、修改健身数据表，还是有开放和结束时间。
理想情况是时时修改，但考虑到浏览器进程、手机电池状况、缓存等问题，还需讨论解决方案。

### 细节提示
- 广鹤：
	1. 日期输入时候要定义好格式，可以用python内置datetime；、
	2. 给用户开放选择，不用选动作，选了身体部位就可以开始记录；
	
### 达成一致
1. 成员各自的输入和输出
- 广鹤：拿到用户健身数据记录表，输出选定的字段，图形化展示。
- 雨明：输出前端交互，输出路演demo
- 蔡俊：搭建数据库、发开相关接口

2. 开发进度：本周完成mvp

### 下一步行动
待讨论问题：
1. 选取哪些动作来做统计
2. 用户在网页上操作，如果想时时修改，如何设计交互和数据传输
3. 时间维度的查询范围

对于第三点，建议：统计的时间范围，和时间颗粒度；也就是用户可以查询多久以前的数据，可否按天、周、月、年查询；考虑到如果某天数据为空，图形化展示效果不好
