### ISSUE TITLE
24h时间维度的查询范围

### ISSUE THREAD

**Issue by guoyuming** [guoyuming/Fitlog#7]
<- [10月18日第一次zoom线上会议提议 · Issue #6 · guoyuming/Fitlog](https://github.com/guoyuming/Fitlog/issues/6)

统计的时间范围，和时间颗粒度；也就是用户可以查询多久以前的数据，可否按天、周、月、年查询；考虑到如果某天数据为空，图形化展示效果不好

**Comment by littlexiaocai** [comment]
1.选取的动作建议 上肢，核心区域，下肢各选一个经典动作作为MVP。
2.统计的时间颗粒度建议到分钟，可以按天，周，月，年查询，因为时间统计的维度，没有区分动作，是所有动作时间的综合，所以如果某天数据为空，可以参考iphone原生的睡眠统计界面，如下所示为按周显示的界面。
![img_4509](https://user-images.githubusercontent.com/30562762/31726920-ca5fbf00-b45a-11e7-9ea3-246f7ba9f513.PNG)

如下所示为按月显示的界面。
![img_4510](https://user-images.githubusercontent.com/30562762/31726944-e6daf1f4-b45a-11e7-9d54-929743812488.PNG)

**Comment by littlexiaocai** [comment]
### 关于实时修改数据的交互
既然是实时修改，其目的就是为了让用户用完就走，不用在网页上停留过多的时间，按照这个逻辑，用户每做完一个动作，就应该打开网页，只记录当前这个动作，然后下次打开网页，再记录下一个动作，后台根据日期将这些动作自动汇总到一起。

### 疑问
如果实时修改，用户是否需要对每个动作都独立记录运动时间，如果不需要，如何统计整体的运动时间。

**Comment by guoyuming** [comment]
@littlexiaocai  OK，只统计运动总时间，不分别统计各个运动时间。总时间在动作记录表单之外，文字框输入填写，然后与动作记录一起提交。
